### ISSUE TITLE
Comments inline

### ISSUE THREAD

**Issue by j2ghz** [jacobbednarz/atom-language-ini#10]
As you can read on http://en.wikipedia.org/wiki/INI_file#Comments_2 comments don't have to be on line by themselves

**Comment by jacobbednarz** [comment]
I'm not 100% sure on this one as we purposely put this restriction in place via #6 as the python spec mentioned it didn't support inline comments. 

From what I've read, the ability to parse the inline comment comes down to a parser by parser scenario. What do you think?

**Comment by j2ghz** [comment]
That seems to be the truth. I see 2 options:
- Make it optional (if it's possible) (best one)
- Format inline comments, the developer should know whether his parser accepts them
The thrid could be to not format them, but imagine you have to read through a very long ini file and you are not allowed to put the comments to next line.

**Comment by jacobbednarz** [comment]
Hey,
Sorry on the delay in coming back to this.

I'm afraid we can't make this optional as it would then need to be aware of what parser you were attempting to use and sometimes even the developers may not understand the full scope of that. While I'd like to just format it even if all parsers don't support it, I'd feel dirty going against the suggested spec. 

I'm thinking we leave it as is and support the base implementation that doesn't conflict with the spec. What are your thoughts?

**Comment by alexchandel** [comment]
In my experience, INI parsers play it fast and loose with the grammar. In fact, I've run across at least two engineering companies which use TOML-style comments and syntax for their `.ini` files. A permissive grammar is probably better.

**Comment by alexchandel** [comment]
While a strict grammar might help a time-travelling Microsoft employee from the 80's, it's going to be of little use to anyone today.

**Comment by j2ghz** [comment]
@jacobbednarz that leaves 2 options:
- format them, if your parser does not accept them you won't have them in your file, so no difference for you, and the rest is happy
- do not format them, cause trouble for those using them and no difference for the rest

> Make it optional (if it's possible) (best one)
I mean put a checkbox in setting that toggles it globally.

**Comment by jacobbednarz** [comment]
> I mean put a checkbox in setting that toggles it globally.

I'm not sure if you're aware but this repository is also used by [npm](https://www.npmjs.com/package/language-ini) so putting in configuration options may cause issues for people using it (which I definitely don't want to do). 

At this stage, I am much more comfortable leaving it as is (without the inline comments) to match the spec as that seems to be the base implementation supported by the most parsers.
