### ISSUE TITLE
Syntax highlighting gets wonky with nested/concurrent quotes

### ISSUE THREAD

**Issue by jwarner112** [jacobbednarz/atom-language-ini#12]
See the attached screenshot for a guide of how the behaviors seem irregular and improper
![bug](https://cloud.githubusercontent.com/assets/2992409/8286442/9837453c-18d7-11e5-828e-822cb5150d70.PNG)

**Comment by jacobbednarz** [comment]
Hey @jwarner112,
I'm looking at your example and I don't think it's a valid ini file which could explain why this is so odd. In your example, you are demo'ing a _python_ dictionary, not an ini option.

I could be way off track here but let me know your thoughts.

**Comment by jwarner112** [comment]
Hey Jacob,

This could totally be the case. I'm using this at work for a weird hybrid
file and I'm not rightly sure WHAT syntax it follows properly, so that
might be messaging up the highlighter. Dang.

**Comment by jwarner112** [comment]
@jacobbednarz I'm reading [here](https://en.wikipedia.org/wiki/INI_file) that `ini` is an "*informal standard*". With this in mind, even if it's Python dictionaries that I'm putting into it, could the quote nesting be considered more of a general practice and less than an `ini`-specific implementation? For example, you can see in my attached image (line 9) that it sort of improperly un-highlights at the end of the first quote. Shouldn't this be considered erroneous anyway?

If I had sufficient knowledge of the code used to put this together I'd endeavor to try and fix it myself.

**Comment by jacobbednarz** [comment]
yep - the ini specification is _very_ informal however it won't play nicely with things like python dictionaries as that's very language implementation specific (and won't work in say PHP implementations). the ini spec can be seen [here](https://docs.services.mozilla.com/server-devguide/confspec.html) and is extremely basic in terms of what you can achieve with it. 

> For example, you can see in my attached image (line 9) that it sort of improperly un-highlights at the end of the first quote. Shouldn't this be considered erroneous anyway?

the two quoted strings should be an error as you can have either/or, not both however there is also a comma in there which is invalid too.

from what i can see this doesn't appear to be an issue with the highlighter and more of a custom implementation which unfortunately i can't support.

**Comment by jwarner112** [comment]
@jacobbednarz Hey, that's totally fair. I can't expect you to change your whole setup just because my company isn't playing by the rules. Besides, it's just an error on my particular Atom editor. Thanks for checking in!

**Comment by jacobbednarz** [comment]
no problems! thanks again!
