### ISSUE TITLE
also highlight INF files

### ISSUE THREAD

**Issue by thorade** [jacobbednarz/atom-language-ini#13]
Manually setting language to INI results in good looking syntax highlight.
Could you add INF to the supported file types?
Or ist syntax too different and I just did not notice?
What is the difference between ini and inf anyway?

**Comment by jacobbednarz** [comment]
It looks like the `inf` file extension is a plain text file used by microsoft operating systems. The syntax looks _very_ similar so I'd be happy to add it here.

We just need to keep an eye on if the specification ever clashes with `ini`, that `ini` is given the priority.

**Comment by jacobbednarz** [comment]
Fixed via #14 and has been released within v1.11.0.

Thanks :cake:

**Comment by thorade** [comment]
Thank you!
