### ISSUE TITLE
Language name in capital letters

### ISSUE THREAD

**Issue by rugk** [jacobbednarz/atom-language-ini#15]
IMO the name if the language should be written in capital letters. Actually it's ```Ini```, but I think ```INI``` is much better.
That's how it's also written in Notepad++ and in the [Wikipedia article] (https://en.wikipedia.org/wiki/INI_file).

![ini](https://cloud.githubusercontent.com/assets/11966684/9423644/7767adee-48cd-11e5-95d8-e9ec3b7a6df9.png)

Just like PHP isn't ```Php```... :smile:

**Comment by j2ghz** [comment]
https://github.com/jacobbednarz/atom-language-ini/blob/bdb877be795986773f8fc5a25915e3a298d84d4d/grammars/ini.cson#L5

**Comment by rugk** [comment]
Okay, okay... https://github.com/jacobbednarz/atom-language-ini/pull/16 :smile:
