### ISSUE TITLE
Troubles with simple coma

### ISSUE THREAD

**Issue by Zacland** [jacobbednarz/atom-language-ini#21]
Here is my example :

![atom_ini_color](https://cloud.githubusercontent.com/assets/10140441/11373486/cb80b1d8-92d2-11e5-9731-d58278397d2c.png)

The coma for "l'exercice" change the syntaxe color (but it won't)
It don't do if I double the coma, but I don't want to have "double coma" to have a good syntaxe color.

**Comment by jacobbednarz** [comment]
@Zacland from the looks of this, the example above isn't a valid ini section. to use `'` in the middle, you will need to either quote the whole line (which tells the parser it's a string) or escape the `'`. i've ran this through a couple of tests and they all seem to choke one way or another on this so i think to be safe, you'll want to quote this one especially considering `ini` is such a loose spec.

**Comment by Zacland** [comment]
Hello and thanks for response.
I'm ok with you with the fact that text is not really an .ini file but the reason why i say you this mistake is because Sublime Text have a good interpretation of it...

![atom_ini_color2](https://cloud.githubusercontent.com/assets/10140441/11391962/c3466178-9356-11e5-833d-dab0cd3faa55.png)

You did a good job, I just wanted to try to find a similar operation between the two software ;)
