### ISSUE TITLE
Colons in headers

### ISSUE THREAD

**Issue by rewritten** [jacobbednarz/atom-language-ini#22]
In many dialects of the INI format, one is allowed to use colons in section headers (for instance in python ConfigParser - see http://supervisord.org/configuration.html for examples). Would it be possible to have those section headers highlighted as such? Right now they are highlighted as a name/value pair, separated on the colon.

**Comment by jacobbednarz** [comment]
sounds like a reasonable request! will you put together the pull request for it? or would you like me to?

**Comment by rewritten** [comment]
@jacobbednarz I don't know enough about the specific priorities of the grammars, it would be really great if you do it... :smile: :clap: :pray:
