### ISSUE TITLE
Quotes in values break syntax

### ISSUE THREAD

**Issue by nomaed** [jacobbednarz/atom-language-ini#23]
Let's say I have an .ini file like this:

```ini
[Section_A]
SomeText=Something
TextWithQuote=Text's quote breaks syntax

[Section_B]
NormalText=Something Else
TextWithQuote=This text's quote returns to normal mode

[Section_C]
QuotedText="This shows fine"
SingleQuoted='This is also okay'
```

From everything I can find, and also comparing with VIM's syntax highlighting, if the whole value is not surrounded by quotes, it's totally okay to add single quotes without matching pairs in the values, and they should be considered as part of the value, without spanning to multiple lines.

I see that GitHub's highlighter also has the same behavior, although it looks to be that it's not the correct one.

**Comment by jacobbednarz** [comment]
I'm not quite sure if the behaviour your expecting is correct as from all the implementations I've seen, it would throw a syntax error. To include a quote or double quote character it needs to be escaped inside of quotes or double quotes to be declared a string. 

As I've mentioned in other issues, INI is a very very loose specification so to be sure it works as intended I would be quoting them correctly and not relying on the equals operator to declare the beginning of the value. 

My apologies on the delay in getting back to this, it got lost amongst some other alerts.
