### ISSUE TITLE
Add support for numbers

### ISSUE THREAD

**Issue by avindra** [jacobbednarz/atom-language-ini#24]
Hi, I think it would be nice to add support for numbers. For example, consider:

``` ini
extension=oci8.so
expose_php=off

error_reporting=32767
```

It would be nice to see `32767` highlighted as a number.

**Comment by jacobbednarz** [comment]
Would :heart: to see a pull request for this!

**Comment by jordanbrauer** [comment]
@jacobbednarz Was just looking for this too. I think `true` and `false` would be great to add in with numbers as well. I forked the repo and am going to mess around with it - maybe I will make a PR for this before someone else does :)

**Comment by jordanbrauer** [comment]
Added this feature to my PR.

**Comment by avindra** [comment]
check his pr! https://github.com/jacobbednarz/atom-language-ini/pull/36
