### ISSUE TITLE
Support double forward slash for comments

### ISSUE THREAD

**Issue by Keith94** [jacobbednarz/atom-language-ini#32]
Some ini files that I downloaded use `//` to start a comment in the file. But it seems only `;` and `#` is supported by language-ini. I'm looking for a way to include `//` for comments as well.

**Comment by jacobbednarz** [comment]
I've looked in all the specs for ini and cannot see anywhere that mentions double slashes should be an accepted form of comments. 

Is there a specific implementation that allows double slashes to be used?

**Comment by Keith94** [comment]
Not that I'm aware of, but JavaScript syntax uses forward slashes for comments, so it must have been assumed to use them in INI as well.

**Comment by jacobbednarz** [comment]
Unfortunately I don't really want to be adding syntaxes to the ini package that fall outside the spec. Ini itself is already very loose and if someone comes across a file with `//` for comments, it should raise red flags that something isn't quite right.

**Comment by Keith94** [comment]
Fair enough, I'll raise an issue with the authors and see about getting it changed. Thanks for the reply.
