### ISSUE TITLE
.desktop files considering ';' as a line comment

### ISSUE THREAD

**Issue by tristan957** [jacobbednarz/atom-language-ini#33]
Currently the syntax highlighting is considering the semicolon as a line comment although that is not what the character does in a .desktop file.

![semicolon](https://cloud.githubusercontent.com/assets/11936772/23454263/65accc36-fe31-11e6-87a6-929799e781ec.png)

**Comment by jacobbednarz** [comment]
@tristan957 I've taken a crack at this in #34 by splitting out the grammars based on file extensions. Do you mind giving that a run and let me know if it fixes the issue?

**Comment by tristan957** [comment]
Yea I don't mind. Has the update been pushed to atom already?

**Comment by jacobbednarz** [comment]
Nope, you'll need to check out the branch to run it.

**Comment by tristan957** [comment]
Worked like a charm

**Comment by jacobbednarz** [comment]
Released via v1.19.0

**Comment by Alhadis** [comment]
@jacobbednarz Are all the `.desktop` files identifiable from a line which says `[Desktop Entry]`?

If so, it might be cleaner and more maintainable to add a separate rule for Desktop-only blocks which includes every pattern-rule *except* the problematic semicolons.

Also, uh, not a good look when manually assigning a file's grammar through the grammar-selector.... :(
<img src="https://user-images.githubusercontent.com/2346707/28051861-958ad30e-664a-11e7-9889-7fe5f441670e.png" width="370" alt="Figure 1" />
