### ISSUE TITLE
please publish module to npm

### ISSUE THREAD

**Issue by bcoe** [jacobbednarz/atom-language-ini#4]
Could you please publish the ini module to npm? We are using the same highlighting engine as Atom now, and would like to add your grammar:

https://www.npmjs.com/package/polyglot-readme

**Comment by jacobbednarz** [comment]
I've pushed this one to npm - https://www.npmjs.com/package/language-ini

I haven't used npm much, so don't hesitate to let me know if something isn't quite right.

**Comment by bcoe** [comment]
@jacobbednarz thank you! worked like a charm:

![screen shot 2015-02-14 at 3 52 11 pm](https://cloud.githubusercontent.com/assets/194609/6201491/33229fae-b462-11e4-80f3-e91b65edb58c.png)
