### ISSUE TITLE
Duplicated entry in Grammar Selection

### ISSUE THREAD

**Issue by senki** [jacobbednarz/atom-language-ini#40]
Atom: 1.29.0
atom-language-ini: 1.20.0
OS: macOS

On the Grammar Selection Palette, the INI duplicated.

See example:
![screen shot 2018-08-04 at 15 37 02](https://user-images.githubusercontent.com/459353/43673882-ab11bfa0-97fc-11e8-8afa-550bbe6c6bf9.png)

**Comment by wesinator** [comment]
This fix hasn't been released on atom.io yet

**Comment by jacobbednarz** [comment]
Cheers, just released this via v1.21.0.

**Comment by wesinator** [comment]
Thank you sir !
