### ISSUE TITLE
.desktop and ini grammar conflict

### ISSUE THREAD

**Issue by wesinator** [jacobbednarz/atom-language-ini#42]
Both grammars have the same `scopeName`, which [should be unique](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#basic-fields)

Also, from https://github.com/jacobbednarz/atom-language-ini/issues/33#issuecomment-314324354
> @jacobbednarz Are all the .desktop files identifiable from a line which says [Desktop Entry]?

> If so, it might be cleaner and more maintainable to add a separate rule for Desktop-only blocks which includes every pattern-rule except the problematic semicolons.

**Comment by jacobbednarz** [comment]
> @jacobbednarz Are all the .desktop files identifiable from a line which says [Desktop Entry]?

From the documentation, it looks like it however it is really just INI with some additional bits and pieces so I can't be certain.

> If so, it might be cleaner and more maintainable to add a separate rule for Desktop-only blocks which includes every pattern-rule except the problematic semicolons.

Happy to review a PR for this!

**Comment by TehWan** [comment]
I added, locally through the `file-types` package, support for `.conf` files to be `source.ini` and it considers them as `.desktop` instead of `INI`.

Here's a PR to fix this issue.

**Comment by jacobbednarz** [comment]
fixed in #47
