### ISSUE TITLE
I just wanted to leave a thanks.

### ISSUE THREAD

**Issue by rehierl** [jacobbednarz/atom-language-ini#45]
I currently have to edit a lot of configuration files of various different programs, each of which uses a slightly different syntax. So all I needed for the moment was some means to at least easily distinguish the configuration directives from all the comment lines.

As minor as your package might seem ... Thanks for uploading it!

**Comment by jacobbednarz** [comment]
Appreciate the kind words! 🙌 I’m you are finding it useful!
