### ISSUE TITLE
Missing highlights

### ISSUE THREAD

**Issue by lra** [jacobbednarz/atom-language-ini#5]
According to the python stdlib to parse and generate INIs:
- section names can have spaces in the name, e.g. `blah blih = something`. They are not hilighted
- Comments are only for lines starting with `#` or `;`, you cannot have a comment starting at the middle of a line

source: https://docs.python.org/2/library/configparser.html

Want any PR for those?

**Comment by jacobbednarz** [comment]
Yep! I think both requests are quite valid.

**Comment by lra** [comment]
Sorry I switched back to ST3, I won't have time to do this, but feel free to fix it! ;)

**Comment by jacobbednarz** [comment]
No problem! Will pick this one up and get it fixed. Thanks again for letting me know.

**Comment by jacobbednarz** [comment]
@lra do you mind #6 locally and giving it a run? I've updated it to include your suggestions.

**Comment by lra** [comment]
How can I try?

**Comment by jacobbednarz** [comment]
if you run the following commands it should pull down the branch and allow you to test it

- `git clone https://github.com/jacobbednarz/atom-language-ini.git -b add-missing-highlights`
- `atom --dev`
- open an ini file and set the grammar correctly (you may have two options for 'ini' so try them both as one will be the stable version and the other will be the development one)

**Comment by jacobbednarz** [comment]
released as v1.9.0

**Comment by lra** [comment]
#WFM ;)
